version: '3.8'

volumes:
  fake_payment_getaway:

services:
  fake_payment_gateaway:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: fake_pg
    volumes:
      - fake_payment_getaway:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "127.0.0.1:5433:5432"
